apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: prod
  labels:
    role: api
    env: prod
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: api
        image: 825765396418.dkr.ecr.us-east-1.amazonaws.com/todo-backend    
        securityContext:
          seccompProfile:
            type: RuntimeDefault 
          runAsNonRoot: true  # Ensure the container runs as a non-root user
          runAsUser: 1000     # Specify a non-root UID
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            add: ["NET_BIND_SERVICE"]
            drop: ["ALL"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: MONGO_CONN_STR
            valueFrom:
              secretKeyRef:
                name: mongo-connection-sec
                key: MONGO_CONN_STR
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-user-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-user-sec
                key: password
        ports:
        - containerPort: 3500
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3500
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /started
            port: 3500
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30

         