apiVersion: apps/v1
kind: StatefulSet
metadata: 
  namespace: prod
  name: mongodb
spec: 
  serviceName: "mongo-svc"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels: 
        app: mongodb
    spec: 
    
      containers:
      - name: mongodb
        image: mongo
        command:
          - "mongod"
          - "--wiredTigerCacheSizeGB"
          - "0.25"
          - "--bind_ip"
          - "0.0.0.0"
          - "--unixSocketPrefix"
          - "/data/db"
        ports:
        - containerPort: 27017
        env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-user-sec
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-user-sec
                key: password
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            add: ["NET_BIND_SERVICE"]
            drop: ["ALL"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
      initContainers:
        - name: volume-permission-fix
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data/db"]
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
  
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
