apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: prod
  labels:
    app: mongodb-svc
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None  # Headless service for direct pod access
  selector:
    app: mongodb
