apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: prod
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 825765396418.dkr.ecr.us-east-1.amazonaws.com/todo-frontend
        securityContext:
          seccompProfile:
            type: RuntimeDefault 
          runAsNonRoot: true  # Ensure the container runs as a non-root user
          runAsUser: 1000     # Specify a non-root UID
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            add: ["NET_BIND_SERVICE"]
            drop: ["ALL"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://api/api/tasks"
        ports:
        - containerPort: 3000

