---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: g628t-todo-eks-developer-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "secrets", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "ingresses"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: g628t-todo-eks-developer-rolebinding
subjects:
- kind: Group
  name: g628t-todo-eks-developer-group  # The name of the group in your IAM or identity provider
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: g628t-todo-eks-developer-role  # Reference to the ClusterRole created above
  apiGroup: rbac.authorization.k8s.io
